// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package top.zhengyiwoaini.netty.zl07.proto;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:top.zhengyiwoaini.netty.zl07.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realname = 2;</code>
   * @return The realname.
   */
  String getRealname();
  /**
   * <code>string realname = 2;</code>
   * @return The bytes for realname.
   */
  com.google.protobuf.ByteString
      getRealnameBytes();
}
