// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package top.zhengyiwoaini.netty.zl07.proto;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_top_zhengyiwoaini_netty_zl07_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_top_zhengyiwoaini_netty_zl07_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_top_zhengyiwoaini_netty_zl07_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_top_zhengyiwoaini_netty_zl07_MyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rStudent.proto\022\034top.zhengyiwoaini.netty" +
      ".zl07\"\035\n\tMyRequest\022\020\n\010username\030\001 \001(\t\"\036\n\n" +
      "MyResponse\022\020\n\010realname\030\002 \001(\t2~\n\016StudentS" +
      "ervice\022l\n\025GetRealNameByUsername\022\'.top.zh" +
      "engyiwoaini.netty.zl07.MyRequest\032(.top.z" +
      "hengyiwoaini.netty.zl07.MyResponse\"\000B.\n\034" +
      "top.zhengyiwoaini.netty.zl07B\014StudentPro" +
      "toP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_top_zhengyiwoaini_netty_zl07_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_top_zhengyiwoaini_netty_zl07_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_top_zhengyiwoaini_netty_zl07_MyRequest_descriptor,
        new String[] { "Username", });
    internal_static_top_zhengyiwoaini_netty_zl07_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_top_zhengyiwoaini_netty_zl07_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_top_zhengyiwoaini_netty_zl07_MyResponse_descriptor,
        new String[] { "Realname", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
